### ISSUE TITLE
pyHyp doesn't work with numpy 1.24

### ISSUE THREAD

**Issue by A-CGray** [mdolab/pyhyp#69]
## Description

Self explanatory. We are trying to update the "latest" docker images to numpy 1.24 (https://github.com/mdolab/docker/pull/208) and getting the error below in all the pyHyp tests. This error looks pretty much identical to https://github.com/mdolab/adflow/issues/256 so the solution will likely also be similar

### Steps to reproduce issue

1. Install numpy v1.24
2. Run pyHyp tests

### Current behavior

```text
2023-01-17T17:05:27.9879234Z (mpi) ./test_all_examples.py:TestExamples.test_sphere ... FAIL (00:00:0.94, 315 MB)
2023-01-17T17:05:27.9880090Z Traceback (most recent call last):
2023-01-17T17:05:27.9881809Z   File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/testflo/test.py", line 418, in _try_call
2023-01-17T17:05:27.9886788Z     func()
2023-01-17T17:05:27.9887811Z   File "/home/***/repos/pyhyp/tests/./test_all_examples.py", line 98, in test_sphere
2023-01-17T17:05:27.9888961Z     from examples.sphere.runSphere import volumeFile, commonOptions
2023-01-17T17:05:27.9889972Z   File "/home/***/repos/pyhyp/tests/../examples/sphere/runSphere.py", line 55, in <module>
2023-01-17T17:05:27.9891336Z     hyp = pyHypMulti(options=options, commonOptions=commonOptions, skipList=skipList)
2023-01-17T17:05:27.9892759Z   File "/home/***/repos/pyhyp/tests/../pyhyp/pyHyp.py", line 225, in __init__
2023-01-17T17:05:27.9893807Z     hypGrid = pyHyp(comm, options, debug)
2023-01-17T17:05:27.9895165Z   File "/home/***/repos/pyhyp/tests/../pyhyp/pyHyp.py", line 424, in __init__
2023-01-17T17:05:27.9895976Z     self._setOptions()
2023-01-17T17:05:27.9896977Z   File "/home/***/repos/pyhyp/tests/../pyhyp/pyHyp.py", line 763, in _setOptions
2023-01-17T17:05:27.9898101Z     self.hyp.hypinput.sourcestrengthfile = self._expandString("")
2023-01-17T17:05:27.9899552Z ValueError: 0-th dimension must be 512 but got 0 (not defined).
```

### Expected behavior
All tests pass

**Comment by sseraj** [comment]
pyHyp works with numpy up to 1.23. See mdolab/adflow#256 for discussion on updating to 1.24.

**Comment by eirikurj** [comment]
The issue described here (and in https://github.com/mdolab/adflow/issues/256) should be resolved when 1.24.3 is released.
