### ISSUE TITLE
problem reading exports from GMSH

### ISSUE THREAD

**Issue by ews-ffarella** [mdolab/pyhyp#84]
**Edit: I will try to compile GMSH from source  on the mdolab image and let you know**

I am trying to read multi-block grid generatey by GMSH version 4.12.2 but somehow it fails.

The code to generate the surface is:

```
lc = 100;
cx = 324925.0;
cy = 5216025.0;
s = 3000.0;
r = 16000.0;


// Number of cells at inner square
Ns = 12;
// Number of cells between inner square and circle
Ni = 36;




// Horizontal gradings
blockGradi = 1.1;
blockGrads =  1.0;

// Inner square side curvature - 0.4
scr = 1.1;
sc = s * scr;


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //


// 45 degree points angle
a0 = -45;
a1 = -135;
a2 = 135;
a3 = 45;

// Half of 45 degree points angle
ea0 = 0;
ea1 = -90;
ea2 = 180;
ea3 = 90;

ca0 = Cos((Pi/180)*a0);
ca1 = Cos((Pi/180)*a1);
ca2 = Cos((Pi/180)*a2);
ca3 = Cos((Pi/180)*a3);

sa0 = Sin((Pi/180)*a0);
sa1 = Sin((Pi/180)*a1);
sa2 = Sin((Pi/180)*a2);
sa3 = Sin((Pi/180)*a3);

cea0 = Cos((Pi/180)*ea0);
cea1 = Cos((Pi/180)*ea1);
cea2 = Cos((Pi/180)*ea2);
cea3 = Cos((Pi/180)*ea3);

sea0 = Sin((Pi/180)*ea0);
sea1 = Sin((Pi/180)*ea1);
sea2 = Sin((Pi/180)*ea2);
sea3 = Sin((Pi/180)*ea3);

// Inner square x and y position

Point(1) = {cx, cy, 0, lc};


Point(11) = {cx-s, cy-s, 0, lc};
Point(12) = {cx-s, cy+s, 0, lc};
Point(13) = {cx+s, cy+s, 0, lc};
Point(14) = {cx+s, cy-s, 0, lc};


Point(21) = {cx+r*ca1, cy+r*sa1, 0, lc};
Point(22) = {cx+r*ca2, cy+r*sa2, 0, lc};
Point(23) = {cx+r*ca3, cy+r*sa3, 0, lc};
Point(24) = {cx+r*ca0, cy+r*sa0, 0, lc};


Point(31) = {cx-sc, cy, 0, lc};
Point(32) = {cx, cy+sc, 0, lc};
Point(33) = {cx+sc, cy, 0, lc};
Point(34) = {cx, cy-sc, 0, lc};


Circle(1) = {21, 1, 22};
Circle(2) = {22, 1, 23};
Circle(3) = {23, 1, 24};
Circle(4) = {24, 1, 21};



// Gmsh provides other curve primitives than stright lines: splines,
// B-splines, circle arcs, ellipse arcs, etc. Here we define a new
// circle arc, starting at point 14 and ending at point 16, with the
// circle's center being the point 15:

Spline(21) = {11,31,12};
Spline(22) = {12,32,13};
Spline(23) = {13,33,14};
Spline(24) = {14,34,11};


Line(31) = {11, 21};
Line(32) = {12, 22};
Line(33) = {13, 23};
Line(34) = {14, 24};


Curve Loop(1) = {21, 22, 23, 24};
Surface(1) = {1};

Curve Loop(11) = {1, -32, -21, 31};
Surface(11) = {11};

Curve Loop(12) = {32, 2, -33, -22};
Surface(12) = {12};

Curve Loop(13) = {33, 3, -34, -23};
Surface(13) = {13};

Curve Loop(14) = {34, 4, -31, -24};
Surface(14) = {14};


Transfinite Curve {1, 2, 3, 4} = Ni+1 Using Progression 1.0;
Transfinite Curve {21, 22, 23, 24} = Ni+1 Using Progression 1.0;
Transfinite Curve {31, 32,33,34} = Ns+1 Using Progression blockGradi;


Transfinite Surface {1} = {11, 12, 13, 14};
Transfinite Surface {11} = {21, 22, 12, 11};
Transfinite Surface {12} = {22, 23, 13, 12};
Transfinite Surface {13} = {23, 24, 14, 13};
Transfinite Surface {14} = {24, 21, 11, 14};


Recombine Surface {1, 11, 12, 13, 14};

Physical Curve("LEFT") = {1};
Physical Curve("TOP") = {2};
Physical Curve("RIGHT") = {3};
Physical Curve("BOTTOM") = {4};
Physical Surface("TERRAIN1") = {1};
Physical Surface("TERRAIN2") = {11};
Physical Surface("TERRAIN3") = {12};
Physical Surface("TERRAIN4") = {13};
Physical Surface("TERRAIN5") = {14};


Mesh 2;

Mesh.Smoothing = 0;
Mesh.RecombineAll = 1;
Mesh.Smoothing = 0;


Mesh.CgnsExportStructured = 1;
Mesh.Format = 32;	//CGNS fails
// Mesh.Format = 28;	//P3D
```

So I export the data using the PLOT3D Driver, and `pyhyp` can load it. Somehow, the normals are inverted, but I can live with it.
Now, Paraview 5.11.2 can read the CGNS output generated by GMSH (Mesh.Format = 32).  So I would like to do a bit of processing, show below, modify the output of GMSH, and save it to VTM and then CGNS  from paraview.

```python
baseDir = os.path.dirname(os.path.abspath(__file__))
surfaceFile = os.path.join(baseDir, "circular_domain.p3d")
print(surfaceFile)
assert os.path.isfile(surfaceFile), surfaceFile



elevFile = os.path.join(baseDir, "grossglockner_elevation_data.vts")
print(elevFile)
assert os.path.isfile(elevFile), elevFile

import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk

dem_reader = vtk.vtkXMLStructuredGridReader()
dem_reader.SetFileName(elevFile)
dem_reader.Update()
dem = dem_reader.GetOutput()
dem_pts = vtk_to_numpy(dem.GetPoints().GetData())
dem_pts[:, 2] = 0
pts = vtk.vtkPoints()
pts.SetData(numpy_to_vtk(dem_pts))
dem.SetPoints(pts)


if 1:   
    reader = vtk.vtkCGNSReader()
    reader.SetFileName("circular_domain.cgns")
    reader.Update()

    _org = reader.GetOutput()
    out = _org.GetBlock(0)
    for b in range(out.GetNumberOfBlocks()):
        block = out.GetBlock(b)
        pdata = vtk.vtkPolyData()
        pdata.SetPoints(block.GetPoints())
        # print(pdata.GetPoints().GetNumberOfPoints())
        probeFilter = vtk.vtkProbeFilter()
        probeFilter.SetInputData(pdata)
        probeFilter.SetSourceData(dem)
        probeFilter.Update()
        z = vtk_to_numpy(probeFilter.GetOutput().GetPointData().GetArray("Elevation"))
        print((z.min(), z.max()))
        pts3d = vtk_to_numpy(block.GetPoints().GetData())
        pts3d[:, 2] = -z
        pts = vtk.vtkPoints()
        pts.SetData(numpy_to_vtk(pts3d))
        block.SetPoints(pts)
    writer = vtk.vtkXMLMultiBlockDataWriter()
    writer.SetFileName("circular_domain_scaled.vtm")
    writer.SetInputData(_org)
    writer.Update()

# Wish i could save from VTK to CGNS
# But the we can load it in Paraview and re-export as CGNS

    

options = {

    # ---------------------------
    "inputFile": surfaceFile,
    "fileType": "PLOT3D",
    "unattachedEdgesAreSymmetry": False,
    "outerFaceBC": "farfield",
    "autoConnect": True,

...

```

but somehow, the file is still corrupted. Any idea where this comes from? 

![image](https://github.com/mdolab/pyhyp/assets/13105859/b2d5e496-67a2-40bc-94d5-1bde1c283273)

This is what my CGNS looks like in Paraview

![image](https://github.com/mdolab/pyhyp/assets/13105859/a9203307-aa07-47e8-9435-3173c521fe20)

I must point out that I am running it in a container and that the files are written on a CIFS volume. I will try to write them under '/tmp', maybe this could be help. 

Thanks

**Comment by ews-ffarella** [comment]
OK, this solved it (assuming your are using the docker image)

This is taken from https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/utils/docker/Dockerfile.ubuntu20.04

```bash

echo temppass | sudo -S apt update -yqq
echo temppass | sudo -S apt install -yqq libgl1-mesa-dev libxi-dev libxmu-dev mesa-common-dev cmake g++ gfortran clang libhdf5-dev libopenmpi-dev libfltk1.3-dev 
echo temppass | sudo -S apt-get install -yqq apt-utils git wget python3 python3-numpy python3-scipy python3-pip swig clang-tidy emacs-nox valgrind texlive texlive-latex-recommended texlive-latex-extra texinfo fonts-cmu libslepc-complex3.12-dev python3-dev libopenblas-dev libfreetype6-dev tcl-dev tk-dev  libxft-dev libxinerama-dev libxcursor-dev libxfixes-dev libocct-foundation-dev libocct-data-exchange-dev libocct-ocaf-dev libboost-dev cargo gcovr ftp

cd $HOME/packages

wget https://gitlab.onelab.info/gmsh/gmsh/-/archive/gmsh_4_12_2/gmsh-gmsh_4_12_2.tar.gz  && tar -xf gmsh-gmsh_4_12_2.tar.gz && rm -f gmsh-gmsh_4_12_2.tar.gz && mv gmsh-gmsh_4_12_2 gmsh-4.12.2


cd $HOME/gmsh-4.12.2

mkdir build && cd build

CGNS_ROOT=$HOME/packages/CGNS-4.4.0/opt-gcc  cmake \
	-DCMAKE_INSTALL_PREFIX=$HOME/packages/gmsh-4.12.2/opt-gcc \
	-DCMAKE_BUILD_TYPE=Release \
	-DENABLE_BUILD_SHARED=1 \
	-DENABLE_PRIVATE_API=1 \
	-DENABLE_CGNS=ON \
	-DENABLE_PETSC=ON \
	-DENABLE_MPI=ON \
	-DENABLE_OPENMP=ON \
	-DENABLE_PETSC4PY=ON \
	-DOPENGL_GL_PREFERENCE=LEGACY \
	.. 
	

make -j8 shared && make -j8 install && cd .. && rm -rf build
export PATH="$HOME/packages/gmsh-4.12.2/opt-gcc/bin:$PATH"
```

Now i can at least run `cgnscheck` on my output

**Comment by ews-ffarella** [comment]
Now i get this errror for `cgnscheck circular_domain.cgns`.


```
reading CGNS file circular_domain.cgns

reading base "circular_domain.cgns"
reading zone "TERRAIN S00001"
reading zone "TERRAIN S00011"
reading zone "TERRAIN S00012"
reading zone "TERRAIN S00013"
reading zone "TERRAIN S00014"

checking base "circular_domain.cgns"

checking zone "TERRAIN S00001"
WARNING:No family name declared for zone "TERRAIN S00001".It is a recommended practice to associate one.
  checking coordinates "GridCoordinates"
    checking coordinate "CoordinateX"
WARNING:dataclass not given
    checking coordinate "CoordinateY"
WARNING:dataclass not given
    checking coordinate "CoordinateZ"
WARNING:coordinate range is 0
WARNING:dataclass not given
  checking boundary conditions
  checking BC "C00021"
    checking BC interface
  checking BC "C00022"
    checking BC interface
  checking BC "C00023"
    checking BC interface
  checking BC "C00024"
    checking BC interface
  checking zone grid connectivity "ZoneGridConnectivity"
  checking 1to1 connectivity "C00021 (S00001 & S00011)"
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00022 (S00001 & S00012)"
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00023 (S00001 & S00013)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00024 (S00001 & S00014)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface

checking zone "TERRAIN S00011"
WARNING:No family name declared for zone "TERRAIN S00011".It is a recommended practice to associate one.
  checking coordinates "GridCoordinates"
    checking coordinate "CoordinateX"
WARNING:dataclass not given
    checking coordinate "CoordinateY"
WARNING:dataclass not given
    checking coordinate "CoordinateZ"
WARNING:coordinate range is 0
WARNING:dataclass not given
  checking boundary conditions
  checking BC "C00001"
    checking BC interface
  checking BC "C00032"
    checking BC interface
  checking BC "C00021"
    checking BC interface
  checking BC "C00031"
    checking BC interface
  checking zone grid connectivity "ZoneGridConnectivity"
  checking 1to1 connectivity "C00032 (S00011 & S00012)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00021 (S00011 & S00001)"
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00031 (S00011 & S00014)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface

checking zone "TERRAIN S00012"
WARNING:No family name declared for zone "TERRAIN S00012".It is a recommended practice to associate one.
  checking coordinates "GridCoordinates"
    checking coordinate "CoordinateX"
WARNING:dataclass not given
    checking coordinate "CoordinateY"
WARNING:dataclass not given
    checking coordinate "CoordinateZ"
WARNING:coordinate range is 0
WARNING:dataclass not given
  checking boundary conditions
  checking BC "C00032"
    checking BC interface
  checking BC "C00002"
    checking BC interface
  checking BC "C00033"
    checking BC interface
  checking BC "C00022"
    checking BC interface
  checking zone grid connectivity "ZoneGridConnectivity"
  checking 1to1 connectivity "C00032 (S00012 & S00011)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00033 (S00012 & S00013)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00022 (S00012 & S00001)"
    checking 1to1 interface
    checking donor interface

checking zone "TERRAIN S00013"
WARNING:No family name declared for zone "TERRAIN S00013".It is a recommended practice to associate one.
  checking coordinates "GridCoordinates"
    checking coordinate "CoordinateX"
WARNING:dataclass not given
    checking coordinate "CoordinateY"
WARNING:dataclass not given
    checking coordinate "CoordinateZ"
WARNING:coordinate range is 0
WARNING:dataclass not given
  checking boundary conditions
  checking BC "C00033"
    checking BC interface
  checking BC "C00003"
    checking BC interface
  checking BC "C00034"
    checking BC interface
  checking BC "C00023"
    checking BC interface
  checking zone grid connectivity "ZoneGridConnectivity"
  checking 1to1 connectivity "C00033 (S00013 & S00012)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00034 (S00013 & S00014)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00023 (S00013 & S00001)"
    checking 1to1 interface
    checking donor interface

checking zone "TERRAIN S00014"
WARNING:No family name declared for zone "TERRAIN S00014".It is a recommended practice to associate one.
  checking coordinates "GridCoordinates"
    checking coordinate "CoordinateX"
WARNING:dataclass not given
    checking coordinate "CoordinateY"
WARNING:dataclass not given
    checking coordinate "CoordinateZ"
WARNING:coordinate range is 0
WARNING:dataclass not given
  checking boundary conditions
  checking BC "C00034"
    checking BC interface
  checking BC "C00004"
    checking BC interface
  checking BC "C00031"
    checking BC interface
  checking BC "C00024"
    checking BC interface
  checking zone grid connectivity "ZoneGridConnectivity"
  checking 1to1 connectivity "C00034 (S00014 & S00013)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00031 (S00014 & S00011)"
WARNING:start value > end value for range
    checking 1to1 interface
    checking donor interface
  checking 1to1 connectivity "C00024 (S00014 & S00001)"
    checking 1to1 interface
    checking donor interface

checking node names

checking complete
35 warnings (35 shown)
```


And then, in `pyhyp`:

```
At line 1185 of file setup3d.F90 (unit = 7, file = '/home/mdolabuser/work/circular_domain/circular_domain.cgns')
Fortran runtime error: Bad integer for item 1 in list input
```


`cgns_utils info circular_domain.cgns` yields:

```
Traceback (most recent call last):
  File "/home/mdolabuser/.pyenv/versions/3.11.6/bin/cgns_utils", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cgnsutilities/cgns_utils.py", line 797, in main
    curGrid = readGrid(args.gridFile)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdolabuser/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cgnsutilities/cgnsutilities.py", line 2905, in readGrid
    raise Error(
baseclasses.utils.error.Error:
+------------------------------------------------------------------------------+
| Error: The provided BC index '0' is not known to cgnsutilities. Check the    |
| 'BCSTANDARD' dictionary for potential CGNS standard BCs, or add this index   |
| with the correct name to the dictionary.                                     |
+------------------------------------------------------------------------------+

```

**Comment by ews-ffarella** [comment]
Solved it!
If anyone face problems with gmsh output, you can reach out to me. The trick is to use cgns_utilities, modify the BCSTANDARD dict and set the key of wall to 0 before using readGrid. Then, one can loop over the blocks and reset the cgns_type to the desired value
